# Site settings
author: Nastaran
title: My great blog!
header-img: img/home-bg.png
email: nazemian86@gmail.com
copyright_name: Nastaran
description: > # this means to ignore newlines until "baseurl:"
  My blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  na-na15

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
